name: wool-battle
main: ml.mops.woolbattle.Plugin
version: "'indev-SNAPSHOT-1.0"
api-version: 1.19
author: MopsCorporation
description: Plugin for WoolBattle
load: POSTWORLD
commands:
  startgame:
    description: ""
    usage: /startgame
  clearblocks:
    description: ""
    usage: /clearblocks
  stopgame:
    description: ""
    usage: /stopgame
  hardmode:
    description: ""
    usage: /hardmode
  refill:
    description: ""
    usage: /refill
  clearscoreboard:
    description: ""
    usage: /clearscoreboard
  testmode:
    description: ""
    usage: /testmode
  cubicstuff:
    description: ""
    usage: /cubicstuff
  addkills:
    description: ""
    usage: /addkills
  globallangchange:
    description: ""
    usage: /globallangchange
  dominate:
    description: ""
    usage: /dominate
  infinitewool:
    description: ""
    usage: /infinitewool
  globalchat:
    description: ""
    usage: /globalchat
  items:
    description: ""
    usage: /items
  playsong:
    description: ""
    usage: /playsong
  slimetest:
    description: ""
    usage: /slimetest
  name:
    description: ""
    usage: /name
  rank:
    description: ""
    usage: /rank
  kickall:
    description: ""
    usage: /kickall
  customgive:
    description: ""
    usage: /customgive
  loreadd:
    description: ""
    usage: /loreadd
  loreclear:
    description: ""
    usage: /loreclear
  loreremove:
    description: ""
    usage: /loreremove
  nameitem:
    description: ""
    usage: /nameitem
  fly:
    description: ""
    usage: /fly
  announce:
    description: ""
    usage: /announce
  enchantitem:
    description: ""
    usage: /enchantitem
  enchantclear:
    description: ""
    usage: /enchantclear
  kit:
    description: ""
    usage: /kit
  lobby:
    description: ""
    usage: /lobby
  hub:
    description: ""
    usage: /hub
  l:
    description: ""
    usage: /l
  test:
    description: ""
    usage: /test
  vector:
    description: ""
    usage: /vector
  calc:
    description: ""
    usage: /calc
  unbreak:
    description: ""
    usage: /unbreak
  food:
    description: ""
    usage: /food
  color:
    description: ""
    usage: "/color #11ccee"
  colorcodes:
    description: ""
    usage: /colorcodes
  deconstructlore:
    description: ""
    usage: /deconstructlore
  simplevanish:
    description: ""
    usage: /simplevanish
  addflags:
    description: ""
    usage: /addflags
  setrespawntime:
    description: ""
    usage: /setrespawntime
  setcombo:
    description: ""
    usage: /setcombo