name: Build PVP

on:
  push:
    branches:
      - 'main'
      - 'dev/*'
      - 'maven'
    paths:
      - 'apps/pvp/**'

jobs:
  build-plugin:
    name: build-plugin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - name: Set up JDK 17
        uses: actions/setup-java@v3.1.1
        with:
         java-version: '17'
         distribution: 'temurin'
         cache: maven
      - run: mvn install
      - run: mkdir staging && cp apps/pvp/target/*.jar staging
      - name: 'Upload .jar artefact'
        uses: actions/upload-artifact@v3.0.0
        with:
         name: MopsPVPPlugin JAR
         path: staging
