name: Build PVP

on:
  push:
    branches:
      - 'main'
      - 'dev/*'
    paths:
      - 'apps/pvp/**'

jobs:
  build-plugin:
    name: build-plugin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - name: Set up JDK 17
        uses: actions/setup-java@v3.1.1
        with:
         java-version: '17'
         distribution: 'temurin'
         cache: maven
      - name: Build
        run: mvn clean package --projects :pvp
      - run: mkdir staging && cp apps/pvp/target/*.jar staging
      - name: 'Upload .jar artefact'
        uses: actions/upload-artifact@v2.3.1
        with:
         name: MopsPVPPlugin JAR
         path: staging
      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ls
          docker build --tag ${{ steps.IMAGE.outputs.lowercase }} --build-arg JAR_PATH=apps/foo/target/pvp.jar .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE}
