name: Build Lobby

on:
  push:
    paths:
      - 'apps/mops-lobby/**'
      - '.github/workflows/build-mopslobby.yaml'
      - 'libs/mops-base/**'
  pull_request:
    paths:
      - 'apps/mops-lobby/**'
      - '.github/workflows/build-mopslobby.yaml'
      - 'libs/mops-base/**'

jobs:
  build-plugin:
    name: build-plugin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Set up JDK 18
        uses: actions/setup-java@v3.6.0
        with:
          java-version: '18'
          distribution: 'zulu'
          cache: maven
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: 'Install libs and build PVP'
        run: mvn -X install --projects :mops-base,:mops-lobby
      - name: 'Ахуеть как похуй блять какая нахуй разница ёбаный насрал'
        run: rm apps/mops-lobby/target/original-*.jar
      - name: 'Upload .jar artefact of plugin'
        uses: actions/upload-artifact@v3.1.1
        with:
          name: MopsPVP Plugin JAR
          path: apps/mops-lobby/target/*.jar
