name: Build WoolBattle

on:
  push:
    paths:
      - 'apps/wool-battle/**'
      - '.github/workflows/build-woolbattle.yaml'
      - 'libs/mops-base/**'
  pull_request:
    paths:
      - 'apps/wool-battle/**'
      - '.github/workflows/build-woolbattle.yaml'
      - 'libs/mops-base/**'
jobs:
  build-plugin:
    name: build-plugin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Set up JDK 18
        uses: actions/setup-java@v3.4.1
        with:
          java-version: '18'
          distribution: 'zulu'
          cache: maven
      - name: 'Install libs and build plugin for WoolBattle'
        run: mvn install --projects :mops-base,:wool-battle
      - name: 'Upload .jar artefact of plugin'
        uses: actions/upload-artifact@v3.1.0
        with:
          name: WoolBattle Plugin JAR
          path: apps/wool-battle/target/*.jar
