name: Test Dependabot branch

on:
  push:
    branches:
      - '**'
      - '!main'
      - '!dev'
      - 'dev/*'
      - 'dependabot/*'

jobs:
  build-plugins:
    name: build-plugins
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Set up JDK 18
        uses: actions/setup-java@v3.7.0
        with:
          java-version: '18'
          distribution: 'zulu'
          cache: maven
      - name: 'Install libs and build plugins'
        run: mvn install --projects :mops-base,:mops-pvps,:mops-lobby,:wool-battle
      - name: "Move .jar's"
        run: |
          mkdir staging
          cp apps/mops-pvps/target/*.jar staging
          cp apps/wool-battle/target/*.jar staging
          cp apps/mops-lobby/target/*.jar staging
          cp libs/mops-base/target/*.jar staging
      - name: 'Upload .jar artefacts of plugin'
        uses: actions/upload-artifact@v3.1.1
        with:
          name: Mops Plugins
          path: staging/
